import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          nunito.className,
          "bg-gray-800 text-gray-200 antialiased"
        )}
      >
        {children}
      </body>
    </html>
  );
}
